### ISSUE TITLE
Erro ao executar com Java 11 do OpenJDK

### ISSUE THREAD

**Issue by tacianosilva** [chcandido/brModelo#17]
Estou tentando executar o brModelo no Ubuntu 20.04 com Java 11 do OpenJDK, e tenho um erro relacionado com cores. Segue a exception, alguém tem alguma dica de como resolver?

```
Gtk-Message: 22:17:52.730: Failed to load module "canberra-gtk-module"
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Color parameter outside of expected range: Blue
	at java.desktop/java.awt.Color.testColorValueRange(Color.java:310)
	at java.desktop/java.awt.Color.<init>(Color.java:395)
	at java.desktop/java.awt.Color.<init>(Color.java:369)
	at controlador.inspector.InspectorItemSeparador.<init>(InspectorItemSeparador.java:23)
	at controlador.inspector.InspectorItemBase.SuperFactory(InspectorItemBase.java:350)
	at controlador.inspector.Inspector.Add(Inspector.java:211)
	at controlador.inspector.Inspector.lambda$Carrege$0(Inspector.java:496)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at controlador.inspector.Inspector.Carrege(Inspector.java:495)
	at controlador.Editor.PerformInspectorFor(Editor.java:1240)
	at controlador.Diagrama.PerformInspector(Diagrama.java:1574)
	at controlador.Editor.setInspectorEditor(Editor.java:1327)
	at principal.FramePrincipal.DoInit(FramePrincipal.java:116)
	at principal.FramePrincipal.<init>(FramePrincipal.java:75)
	at principal.Aplicacao$1.run(Aplicacao.java:62)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by chcandido** [comment]
Há um bug neste trecho:

    public InspectorItemSeparador(Inspector criador) {
        super(criador);
        Color c = getBackground();
        c = new Color(c.getRed(), c.getGreen(),  c.getBlue() - 15);
        //:BUG CORRIGIDO: Vinicius Oliveira Queiroz.
        setBackground(c);
    }

A depender do retorno da função  getBackground() tem-se um erro no trecho [c.getBlue() - 15].
Será corrigido, obrigado.
________________________________
De: Taciano Morais Silva ***@***.***>
Enviado: segunda-feira, 22 de março de 2021 21:19
Para: chcandido/brModelo ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: [chcandido/brModelo] Erro ao executar com Java 11 do OpenJDK (#17)


Estou tentando executar o brModelo no Ubuntu 20.04 com Java 11 do OpenJDK, e tenho um erro relacionado com cores. Segue a exception, alguém tem alguma dica de como resolver?

Gtk-Message: 22:17:52.730: Failed to load module "canberra-gtk-module"

Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Color parameter outside of expected range: Blue

        at java.desktop/java.awt.Color.testColorValueRange(Color.java:310)

        at java.desktop/java.awt.Color.<init>(Color.java:395)

        at java.desktop/java.awt.Color.<init>(Color.java:369)

        at controlador.inspector.InspectorItemSeparador.<init>(InspectorItemSeparador.java:23)

        at controlador.inspector.InspectorItemBase.SuperFactory(InspectorItemBase.java:350)

        at controlador.inspector.Inspector.Add(Inspector.java:211)

        at controlador.inspector.Inspector.lambda$Carrege$0(Inspector.java:496)

        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)

        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)

        at controlador.inspector.Inspector.Carrege(Inspector.java:495)

        at controlador.Editor.PerformInspectorFor(Editor.java:1240)

        at controlador.Diagrama.PerformInspector(Diagrama.java:1574)

        at controlador.Editor.setInspectorEditor(Editor.java:1327)

        at principal.FramePrincipal.DoInit(FramePrincipal.java:116)

        at principal.FramePrincipal.<init>(FramePrincipal.java:75)

        at principal.Aplicacao$1.run(Aplicacao.java:62)

        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)

        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)

        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)

        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)

        at java.base/java.security.AccessController.doPrivileged(Native Method)

        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)

        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)

        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)

        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)

        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)

        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)

        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)

        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by tacianosilva** [comment]
Depois de pesquisar fiz a mudança do meu tema do Ubuntu (estava com um tema Dark) para um tema padrão.
Depois da mudança do tema o brModelo abriu normalmente.

Valeu!

**Comment by lumifere** [comment]
Também estava tendo esse mesmo problema, após modificar o tema do Ubuntu, o brModelo funcionou novamente
